Init scripts now work on suse,redhat, and debia

diff --git a/client/src/init.d/odap b/client/src/init.d/odap
--- a/client/src/init.d/odap
+++ b/client/src/init.d/odap
@@ -2,32 +2,68 @@
 #
 PIDFILE="/var/run/odap.pid"
 CONF_FILE="/etc/odap/config.ini"
-. /lib/lsb/init-functions
+
+if [ -f /etc/redhat-release -o -f /etc/fedora-release ] ; then
+    DISTRIBUTION="redhat"
+elif [ -f /etc/SuSE-release ] ; then
+    DISTRIBUTION="suse"
+elif [ -f /etc/debian_version ] ; then
+    DISTRIBUTION="debian"
+else
+    DISTRIBUTION="debian"
+fi
+
+# Source function library.
+[ "$DISTRIBUTION" = "redhat" ] && . /etc/init.d/functions
+[ "$DISTRIBUTION" = "suse" ] && . /lib/lsb/init-functions
+[ "$DISTRIBUTION" = "debian" ] && . /lib/lsb/init-functions
+
+
 
 start() {
         if [ ! -f $CONF_FILE ]; then
              echo "You must first run as root \"odap -config\""
              exit 2 
 	fi
-  start-stop-daemon --start --q --pidfile $PIDFILE --exec /usr/bin/odap	
-  if [ "$?" -eq "0" ]; then
-	 echo -e "Starting odap service \033[32m ok\033[0m"
-  else
-	echo -e "Starting odap service \033[31m failed\033[0m"
-  fi 
 
+  RETVAL=
+  if [ "$DISTRIBUTION" = "redhat" ] ; then
+  	echo -n $"Starting odap service"
+        daemon "/usr/bin/odap"
+        RETVAL=$?	
+  else
+  	start-stop-daemon --start --q --pidfile $PIDFILE --exec /usr/bin/odap	
+	RETVAL=$?
+  	if [ "$RETVAL" -eq "0" ]; then
+		echo -e "Starting odap service \033[32m ok\033[0m"
+  	else
+		echo -e "Starting odap service \033[31m failed\033[0m"
+  	fi 
+  fi
+  echo
+  return $RETVAL
 }
 
 stop(){
   echo -n $"Stopping odap service: "
-  start-stop-daemon --stop --q --pidfile $PIDFILE 
-  if [ "$?" -eq "0" ]; then
-         echo -e "Stopping odap service \033[32m ok\033[0m"
+  RETVAL=
+  if [ "$DISTRIBUTION" = "redhat" ] ; then
+	killproc -p "$PIDFILE" -d 10 "$DAEMON"
+	RETVAL="$?"
   else
-        echo -e "Stopping odap service \033[31m failed\033[0m"
+  	start-stop-daemon --stop --q --pidfile $PIDFILE 
+	RETVAL="$?"
+  	if [ "$RETVAL" -eq "0" ]; then
+        	echo -e "Stopping odap service \033[32m ok\033[0m"
+  	else
+        	echo -e "Stopping odap service \033[31m failed\033[0m"
+  	fi
   fi
-  rm -f $PIDFILE
+  [ $RETVAL = 0 ] && rm -f "$PIDFILE" 
+   echo
+  return "$RETVAL"
 }
+
 
 check_for_root() {
   if [ $(id -ur) -ne 0 ]; then
